### ISSUE TITLE
About the electromagnetic

### ISSUE THREAD

**Issue by Kenny840394191** [2083008/GhostChess#4]
Using the magnets to control the chess is a good idea, but how do you ensure that electromagnetic interactions do not affect each other because the distance between the pieces is very close. And how to prevent wrong move?

team 15

**Comment by 2083008** [comment]
We have tried several different magnets to find a balance between magnetic force and size, also ensuring a sufficiently large board so they do not interfere when moving a piece. There is software being written to check valid moves! Cheers
