### ISSUE TITLE
More Hardware Information Required

### ISSUE THREAD

**Issue by 2077762b** [2083008/GhostChess#5]
This is perhaps the most challenging project. I am excited to see how it turns out. Just a few issues to consider:
* It would be great if some PCB design files were added to the repository to help someone replicate the project.
* There appears to be minimal commentary in the code. It would be great if each C++ member function had a comment explaining its purpose.
* Currently it would be extremely difficult to replicate this project. Much further information is required in the README and Wiki sections, particularly explaining the mechanical assembly.

**Team 10**

**Comment by 2083008** [comment]
- Added schematics for the sensory array as well as more documentation
- Added some more comments to the code
- Further help provided for setup of this project as well as section for FAQ/Common issues as these are discovered

Cheers
