### ISSUE TITLE
How is testing going?

### ISSUE THREAD

**Issue by acra6488** [2083008/GhostChess#8]
Hi, this is one of my favourite projects as I think it definitely has some appeal for commercialisation. The idea of chess pieces moving on their own is great!
I would like to see short video footage of the system working when you get around to testing.
Also if you could indicate what problems you have encountered and how you solved them so that other people won't repeat the same mistakes, that would be great!
-Aurelie -Team2

**Comment by 2083008** [comment]
Appreciate it!

Added section for FAQ/Common Issues which will be updated where common mistakes(found by us) and others are found and submitted by people who eventually replicate the project. Cheers
